

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        # Use the action from the master, as we've seen some inconsistencies with @v1
        # Issue: https://github.com/docker/build-push-action/issues/286
        uses: docker/setup-buildx-action@master
        # Only worked for us with this option on 🤷‍♂️
        with:
          install: true
          driver: docker-container

      - name: Cache Docker layers
        uses: actions/cache@v2
        id: cache
        with:
          path: ${{ env.CACHE_FROM_DIR }}
          # Key is named differently to avoid collision
          key: ${{ runner.os }}-${{ env.BUILD_NAME }}-buildx-${{ github.sha }}

      - name: Log into registry aliyun
        if: steps.cache.outputs.cache-hit != 'true'
        uses: aliyun/acr-login@v1
        with:
          login-server: https://registry.cn-hangzhou.aliyuncs.com
          region-id: cn-hangzhou
          username: ${{ secrets.DOCKER_ALI_USER }}
          password: ${{ secrets.DOCKER_ALI_TOKEN }}
      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry dockerhub
        if: steps.cache.outputs.cache-hit != 'true'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Init directory
        run: make init
      # Build and push Docker image with Buildx (don't push on PR)
      - name: Build and push Docker image
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: ./${{ env.BUILD_NAME }}
        run: ./build.sh
