name: Build and Publish centos Image

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
    paths:
      - "centos/**"
      - "util/**"

env:
  NEED_PUSH: 1
  PUSH_TO_OFFICAL: 1
  DOCKER_BUILDKIT: 1
  BUILD_NAME: centos


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry dockerhub
        if: steps.cache.outputs.cache-hit != 'true'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push centos
        uses: docker/build-push-action@v3
        with:
          context: ./centos
          file: ./centos/centos.Dockerfile
          push: true
          tags: yunnysunny/centos:latest
          cache-from: type=registry,ref=yunnysunny/centos:buildcache
          cache-to: type=registry,ref=yunnysunny/centos:buildcache,mode=max
      - name: Update centos description
        uses: peter-evans/dockerhub-description@v2
        if: ${{ github.event_name != 'pull_request' }}
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          repository: yunnysunny/centos
      - name: Build and push jdk11
        uses: docker/build-push-action@v3
        with:
          context: ./centos
          file: ./centos/java.Dockerfile
          push: true
          tags: yunnysunny/jdk11:latest
          cache-from: type=registry,ref=yunnysunny/jdk11:buildcache
          cache-to: type=registry,ref=yunnysunny/jdk11:buildcache,mode=max
      - name: Update jdk11 description
        uses: peter-evans/dockerhub-description@v2
        if: ${{ github.event_name != 'pull_request' }}
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          repository: yunnysunny/jdk11
