name: Build and Publish Docker Image

# refer to https://github.com/actions/starter-workflows/blob/main/ci/docker-publish.yml 

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master

env:
  NEED_PUSH: 1
  PUSH_TO_OFFICAL: 1
  CACHE_FROM_DIR: /tmp/.buildx-cache
  CACHE_TO_DIR: /tmp/.buildx-cache-new
  DOCKER_BUILDKIT: 1


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        # Use the action from the master, as we've seen some inconsistencies with @v1
        # Issue: https://github.com/docker/build-push-action/issues/286
        uses: docker/setup-buildx-action@master
        # Only worked for us with this option on 🤷‍♂️
        with:
          install: true

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          # Key is named differently to avoid collision
          key: ${{ runner.os }}-multi-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-multi-buildx

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry dockerhub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Log into registry aliyun
        if: github.event_name != 'pull_request'
        run: docker login -u ${{ secrets.DOCKER_ALI_USER }} -p ${{ secrets.DOCKER_ALI_TOKEN }} https://registry.cn-hangzhou.aliyuncs.com
      - name: Init directory
        run: make init
      # Build and push Docker image with Buildx (don't push on PR)
      - name: Build and push Docker image
        working-directory: ./
        run: make
      - name: Move cache
        run: make renew